Header header
# requested torque on the left rear wheel in Nm
float64 left_torque
# requested torque on the right rear wheel in Nm
float64 right_torque
# requested steering angle in degrees
float64 steering_angle
# whether the vehicle should steer, or remain in the current steering position without applying force
bool steering_active
# requested brake pressure for the system in bar measured at the front brake circuit
float64 brake_pressure
