# Use to make connections to the hub.

string uri
---
# Return a verbose error string to help with debugging if success fails.
# Strings defined in gateway_comms.msg.Result
int8 result
string error_message

