#!/usr/bin/env python

import sys

from rqt_gui.main import Main
from dataspeed_pds_rqt.pds_gui import PowerDistributionGui

plugin = 'dataspeed_pds_rqt.pds_gui.PowerDistributionGui'
main = Main(filename=plugin)
sys.exit(main.main(sys.argv, standalone=plugin, plugin_argument_provider=PowerDistributionGui.add_arguments))
