#!/usr/bin/env python

import sys

try:
    from coverage import main
except ImportError as exc:
    print("Error: failed to run coverage: {0}".format(exc))

if __name__ == '__main__':
    sys.exit(main())
