version: 2
jobs:
  kinetic:
    docker:
      - image: autonomoustuff/docker-builds:kinetic-ros-base
    steps:
      - checkout
      - run:
          name: Set Up Container
          command: |
            apt-get update -qq
            source `find /opt/ros -name setup.bash | sort | head -1`
            rosdep install --from-paths . --ignore-src -y
            cd ..
            catkin init
            catkin config --extend /opt/ros/$ROS_DISTRO
      - run:
          name: Build
          command: |
            cd ..
            catkin build
      - run:
          name: Run Tests
          command: |
            source `find /opt/ros -name setup.bash | sort | head -1`
            cd ..
            catkin run_tests
            catkin_test_results
    working_directory: ~/src

  lunar:
    docker:
      - image: autonomoustuff/docker-builds:lunar-ros-base
    steps:
      - checkout
      - run:
          name: Set Up Container
          command: |
            apt-get update -qq
            source `find /opt/ros -name setup.bash | sort | head -1`
            rosdep install --from-paths . --ignore-src -y
            cd ..
            catkin init
            catkin config --extend /opt/ros/$ROS_DISTRO
      - run:
          name: Build
          command: |
            cd ..
            catkin build
      - run:
          name: Run Tests
          command: |
            source `find /opt/ros -name setup.bash | sort | head -1`
            cd ..
            catkin run_tests
            catkin_test_results
    working_directory: ~/src

  melodic:
    docker:
      - image: autonomoustuff/docker-builds:melodic-ros-base
    steps:
      - checkout
      - run:
          name: Set Up Container
          command: |
            apt-get update -qq
            source `find /opt/ros -name setup.bash | sort | head -1`
            rosdep install --from-paths . --ignore-src -y
            cd ..
            catkin init
            catkin config --extend /opt/ros/$ROS_DISTRO
      - run:
          name: Build
          command: |
            cd ..
            catkin build
      - run:
          name: Run Tests
          command: |
            source `find /opt/ros -name setup.bash | sort | head -1`
            cd ..
            catkin run_tests
            catkin_test_results
    working_directory: ~/src

  crystal:
    docker:
      - image: autonomoustuff/docker-builds:crystal-ros-core
    steps:
      - checkout
      - run:
          name: Set Up Container
          command: |
            apt update -qq
            echo 'source `find /opt/ros -maxdepth 2 -name local_setup.bash | sort | head -1`' >> $BASH_ENV
            source $BASH_ENV
            rosdep install --from-paths . --ignore-src -y
            mkdir $CIRCLE_PROJECT_REPONAME
            mv `find -maxdepth 1 -not -name . -not -name $CIRCLE_PROJECT_REPONAME` $CIRCLE_PROJECT_REPONAME/
      - run:
          name: Build
          command: |
            cd ..
            colcon build
      - run:
          name: Test
          command: |
            cd ..
            colcon test
            colcon test-result
    working_directory: ~/src

workflows:
  version: 2
  ros_build:
    jobs:
      - kinetic
      - lunar
      - melodic
      - crystal
