#!/usr/bin/env python
# -*- Python -*-
# -*- coding: euc-jp -*-

##
# @file rtcd_python
# @brief RT component server daemon
# @date $Date: $
# @author Noriaki Ando <n-ando@aist.go.jp> and Shinji Kurihara
#
# Copyright (C) 2010
#     Intelligent Systems Research Institute,
#     National Institute of
#         Advanced Industrial Science and Technology (AIST), Japan
#     All rights reserved.

import sys
import rtcd

def main():
  rtcd.main()
  return

if __name__ == "__main__":
  main()
