Header header

# Turn Signal enumeration
TurnSignal turn_signal

# Highbeam headlights / flash to pass enumeration
HighBeam high_beam

# Front Windshield Wipers enumeration
Wiper wiper

# Buttons
bool btn_cc_on_off    # Cruise Control On/Off Toggle
bool btn_cc_res       # Cruise Control Resume
bool btn_cc_cncl      # Cruise Control Cancel
bool btn_cc_set_inc   # Cruise Control Set+
bool btn_cc_set_dec   # Cruise Control Set-
bool btn_cc_gap_inc   # Cruise Control Gap+
bool btn_cc_gap_dec   # Cruise Control Gap-
bool btn_cc_mode      # Cruise Control Mode
bool btn_ld_ok        # Left D-Pad OK
bool btn_ld_up        # Left D-Pad Up
bool btn_ld_down      # Left D-Pad Down
bool btn_ld_left      # Left D-Pad Left
bool btn_ld_right     # Left D-Pad Right

# Faults
bool fault_bus

# Doors
bool door_rear_left
bool door_rear_right
bool door_trunk
