###############################################################################
# Dicj
###############################################################################
#
# Interaface to a typical docking controller
#
###############################################################################

####################
# Goal
####################
# To dock (True) or undock (False)
bool dock

---
####################
# Result
####################

int8 value
string message


int8 SUCCESS = 0
int8 ERROR = 1

---

####################
# Feedback
####################

float32 percentage_completed
