###############################################################################
# Rotate
###############################################################################
#
# Rotates the robot a full 2pi radians.
# Used for the py_trees_ros mocking demos/tests!
#
###############################################################################

####################
# Goal
####################

---
####################
# Result
####################

int8 value
string message


int8 SUCCESS = 0
int8 ERROR = 1

---

####################
# Feedback
####################

float32 percentage_completed
float32 angle_rotated          # in radians
