# Channel index (enum below)
uint8 channel

# Channel Enum
uint8 CHAN_01=0  # Master Ch1
uint8 CHAN_02=1  # Master Ch2
uint8 CHAN_03=2  # Master Ch3
uint8 CHAN_04=3  # Master Ch4
uint8 CHAN_05=4  # Master Ch5
uint8 CHAN_06=5  # Master Ch6
uint8 CHAN_07=6  # Master Ch7
uint8 CHAN_08=7  # Master Ch8
uint8 CHAN_09=8  # Master Ch9
uint8 CHAN_10=9  # Master Ch10
uint8 CHAN_11=10 # Master Ch11
uint8 CHAN_12=11 # Master Ch12
uint8 CHAN_13=12 # Slave  Ch1
uint8 CHAN_14=13 # Slave  Ch2
uint8 CHAN_15=14 # Slave  Ch3
uint8 CHAN_16=15 # Slave  Ch4
uint8 CHAN_17=16 # Slave  Ch5
uint8 CHAN_18=17 # Slave  Ch6
uint8 CHAN_19=18 # Slave  Ch7
uint8 CHAN_20=19 # Slave  Ch8
uint8 CHAN_21=20 # Slave  Ch9
uint8 CHAN_22=21 # Slave  Ch10
uint8 CHAN_23=22 # Slave  Ch11
uint8 CHAN_24=23 # Slave  Ch12
uint8 CHAN_INV1=48 # Master Inverter
uint8 CHAN_INV2=49 # Slave  Inverter

# Request value (enum below)
uint8 request

# Request enum
uint8 OFF=0
uint8 ON=1
uint8 TOGGLE=2
