module SimpleService {
typedef sequence<string> EchoList;
typedef sequence<float> ValueList;
interface MyService
{
  string echo(in string msg);
  EchoList get_echo_history();
  void set_value(in float value);
  float get_value();
  ValueList get_value_history();
};
};
